<a href="https://colab.research.google.com/github/uchechukwuilorah-create/Car-Price-Prediction-model-/blob/main/Genius_intern_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, BaggingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
import pickle

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/car data.csv')
# Load the dataset from a CSV file into a pandas DataFrame named 'df'.
df.head(10)
# Display the first 10 rows of the DataFrame to get an initial look at the data structure and content.

In [ ]:
df.info()
# Display a concise summary of the DataFrame, including data types of columns, non-null values, and memory usage.
# This helps in quickly understanding the completeness and types of features.

In [ ]:
df.isnull()
# Check for null (missing) values in each cell of the DataFrame.
# Returns a boolean DataFrame of the same shape as 'df', where True indicates a missing value.

In [ ]:
df.isnull().sum()
# Calculate the sum of null values for each column in the DataFrame.
# This provides a count of missing entries per feature, which is crucial for data cleaning.

In [ ]:
df.describe()
# Generate descriptive statistics of the numerical columns in the DataFrame.
# This includes count, mean, standard deviation, min, max, and quartile values, offering insights into data distribution.

In [ ]:
#Features=Selling Price, Present price,Year,KMS Driven
# This comment specifies the features of interest for analysis and modeling.

In [ ]:
plt.scatter(df['Year'],df['Selling_Price'], marker='o')
# Create a scatter plot to visualize the relationship between 'Year' and 'Selling_Price'.
plt.title('Year vs Selling Price')
# Set the title of the plot.
plt.xlabel('Year')
# Set the label for the x-axis.
plt.ylabel('Selling Price')
# Set the label for the y-axis.

In [ ]:
plt.scatter(df['Present_Price'],df['Selling_Price'])
# Create a scatter plot to visualize the relationship between 'Present_Price' and 'Selling_Price'.
plt.title('Present vs Selling Price')
# Set the title of the plot.
plt.xlabel('Present Price')
# Set the label for the x-axis.
plt.ylabel('Selling Price')
# Set the label for the y-axis.

In [ ]:
plt.scatter(df['Kms_Driven'],df['Selling_Price'])
# Create a scatter plot to visualize the relationship between 'Kms_Driven' and 'Selling_Price'.
plt.title('Kms_Driven vs Selling Price')
# Set the title of the plot.
plt.xlabel('Kms_Driven')
# Set the label for the x-axis.
plt.ylabel('Selling Price')
# Set the label for the y-axis.

In [ ]:
sns.boxplot(data=df, x='Fuel_Type', y='Selling_Price')
# Create a box plot to visualize the distribution of 'Selling_Price' across different 'Fuel_Type' categories.
# Box plots help in understanding the spread and central tendency of the selling price for each fuel type.
plt.title('Fuel Type vs Selling Price')
# Set the title of the plot.
plt.xlabel('Fuel Type')
# Set the label for the x-axis.
plt.ylabel('Selling Price')
# Set the label for the y-axis.

In [ ]:
#i want to know how many car model are under car name
unique_models = df['Car_Name'].unique()
print(unique_models)

In [ ]:
sns.boxplot(data=df, x ='Car_Name', y='Selling_Price')

In [ ]:
#The car Name have too much data on different models that is why it is overlapping

In [ ]:
sns.heatmap(df.corr(numeric_only=True), annot = True)
# Generate a heatmap of the correlation matrix for all numerical columns in the DataFrame.
# 'numeric_only=True' ensures only numerical columns are considered for correlation.
# 'annot=True' displays the correlation coefficients on the heatmap cells, providing a quick visual summary of relationships between variables.
plt.show()

In [ ]:
#since I can be rewriting multiple features every time, I will change all of them to X then the Target will be y
# Define the feature matrix (X) and the target variable (Y).
# X includes 'Year', 'Present_Price', and 'Kms_Driven' as independent variables.
X = df[['Year', 'Present_Price' , 'Kms_Driven']]
# Y is the 'Selling_Price' column, which is the dependent variable we want to predict.
Y = df['Selling_Price']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state =42)
# Split the dataset into training and testing sets.
# X_train, Y_train: Training features and target variable.
# X_test, Y_test: Testing features and target variable.
# test_size=0.3: 30% of the data will be used for testing, and 70% for training.

In [ ]:
model = LinearRegression()
# Initialize the Linear Regression model.
model.fit(X_train, Y_train)
# Train the Linear Regression model using the training data (X_train, Y_train).

In [ ]:
model.coef_
# Display the coefficients of the trained Linear Regression model.

In [ ]:
model.intercept_
# Display the intercept (bias) of the trained Linear Regression model.

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Display the predicted selling price.
display(prediction)

In [ ]:
Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained Linear Regression model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE) between actual (Y_test) and predicted (Y_pred) values.
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE) between actual (Y_test) and predicted (Y_pred) values.
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score, which indicates the proportion of the variance in the dependent variable that is predictable from the independent variables.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My Linear Regression Model is:{r2_percent:0f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

In [ ]:
model = DecisionTreeRegressor()
# Initialize the Decision Tree Regressor model.
model.fit(X_train,Y_train)
# Train the Decision Tree Regressor model using the training data (X_train, Y_train).

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Display the predicted selling price.
display(prediction)

In [ ]:
Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained Decision Tree Regressor model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE) between actual (Y_test) and predicted (Y_pred) values.
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE) between actual (Y_test) and predicted (Y_pred) values.
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My Decision Tree Model is:{r2_percent:2f} percentage correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

In [ ]:
model = RandomForestRegressor()
# Initialize the Random Forest Regressor model.
model.fit(X_train,Y_train)
# Train the Random Forest Regressor model using the training data (X_train, Y_train).

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Display the predicted selling price.
display(prediction)

In [ ]:
Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained Random Forest Regressor model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE).
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE).
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My Random Forest Model is:{r2_percent:2f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

In [ ]:
model = GradientBoostingRegressor(n_estimators=100)
# Initialize the Gradient Boosting Regressor model with 100 estimators.
model.fit(X_train,Y_train)
# Train the Gradient Boosting Regressor model using the training data (X_train, Y_train).

GradientBoostingRegressor()

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Make a prediction using the trained Gradient Boosting Regressor for a new data point:
# Year=2024, Present_Price=20, Kms_Driven=34000.
display(prediction)
# Display the predicted selling price.

Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained Gradient Boosting Regressor model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE).
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE).
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My Gradient Boosting Model is:{r2_percent:2f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

array([15.90704605])

0.8897686300738687

0.6170387783386996

0.9687517608234425

My Gradient Boosting Model is:96.875176% correct


In [ ]:
model = SVR(kernel='rbf', C=1e3, gamma=0.1)
# Initialize the Support Vector Regressor (SVR) model.
model.fit(X_train,Y_train)
# Train the SVR model using the training data (X_train, Y_train).

SVR(C=1000.0, gamma=0.1)

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Make a prediction using the trained Support Vector Regressor for a new data point:
# Year=2024, Present_Price=20, Kms_Driven=34000.
display(prediction)
# Display the predicted selling price.

Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained Support Vector Regressor model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE).
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE).
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My Support Vector Model is:{r2_percent:2f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

array([4.81516604])

22.356263636148373

3.0880579287744374

0.2148589536826634

My Support Vector Model is:21.485895% correct


In [ ]:
import xgboost as xgb
import lightgbm as lgb

In [ ]:
model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100)
# Initialize the XGBoost Regressor model.
model.fit(X_train, Y_train)
# Train the XGBoost Regressor model using the training data (X_train, Y_train).

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Make a prediction using the trained XGBoost Regressor for a new data point:
# Year=2024, Present_Price=20, Kms_Driven=34000.
display(prediction)
# Display the predicted selling price.

Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained XGBoost Regressor model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE).
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE).
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My XGBoost Regressor Model is:{r2_percent:.2f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

array([16.201345], dtype=float32)

1.0937649395693416

0.6495350249390026

0.9615875101915446

My XGBoost Regressor Model is:96.16% correct


In [ ]:
model = lgb.LGBMRegressor(objective='regression', n_estimators=100)
# Initialize the LightGBM Regressor model.
model.fit(X_train, Y_train)
# Train the LightGBM Regressor.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000279 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 131
[LightGBM] [Info] Number of data points in the train set: 210, number of used features: 3
[LightGBM] [Info] Start training from score 4.573238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -in

LGBMRegressor(objective='regression')

In [ ]:

prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Make a prediction using the trained LightGBM Regressor for a new data point:
# Year=2024, Present_Price=20, Kms_Driven=34000.
display(prediction)
# Display the predicted selling price.

Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained LightGBM Regressor model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE).
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE).
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My LightGBM Regressor Model is:{r2_percent:.2f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

array([17.65358481])

6.115247177680318

1.326683780443851

0.7852355095772946

My LightGBM Regressor Model is:78.52% correct


In [ ]:
model = Lasso(alpha=1.0)
# Initialize the Lasso Regression model with an alpha of 1.0.
model.fit(X_train,Y_train)
# Train the Lasso Regression model using the training data (X_train, Y_train).

Lasso()

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Make a prediction using the trained Lasso Regression for a new data point:
# Year=2024, Present_Price=20, Kms_Driven=34000.
display(prediction)
# Display the predicted selling price.

Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained Lasso Regression model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE).
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE).
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My Lasso Regression Model is:{r2_percent:.2f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

array([13.81873543])

4.5666949748316705

1.456700634868869

0.8396199056735947

My Lasso Regression Model is:83.96% correct


In [ ]:
model = Ridge(alpha=1.0)
# Initialize the Ridge Regression model with an alpha of 1.0.
model.fit(X_train,Y_train)
# Train the Ridge Regression model using the training data (X_train, Y_train)

Ridge()

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Make a prediction using the trained Ridge Regression for a new data point:
# Year=2024, Present_Price=20, Kms_Driven=34000.
display(prediction)
# Display the predicted selling price.

Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained Ridge Regression model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE).
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE).
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My Ridge Regression Model is:{r2_percent:.2f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

array([15.56502419])

4.07101244217949

1.3996041203006846

0.8570280338233489

My Ridge Regression Model is:85.70% correct


In [ ]:
model = BaggingRegressor(n_estimators=100, random_state=42)
# Initialize the Bagging Regressor model with 100 estimators and a random state for reproducibility.
model.fit(X_train, Y_train)
# Train the Bagging Regressor model using the training data (X_train, Y_train).

BaggingRegressor(n_estimators=100, random_state=42)

In [ ]:
prediction = model.predict(pd.DataFrame([[2024, 20, 34000]], columns=X_train.columns))
# Make a prediction using the trained Bagging Regressor for a new data point:
# Year=2024, Present_Price=20, Kms_Driven=34000.
display(prediction)
# Display the predicted selling price.

Y_pred = model.predict(X_test)
# Generate predictions on the test set using the trained Bagging Regressor model.
mse = mean_squared_error(Y_test,Y_pred)
# Calculate the Mean Squared Error (MSE).
mae = mean_absolute_error(Y_test,Y_pred)
# Calculate the Mean Absolute Error (MAE).
r2 = r2_score(Y_test, Y_pred)
# Calculate the R-squared (R2) score.
r2_percent = r2 * 100
# Convert R2 score to a percentage.
display(mse)
display(mae)
display (r2)
# Display MSE, MAE, and R2 score.
print(f"My Bagging Regressor Model is:{r2_percent:.2f}% correct")
# Print the R2 score as a percentage, indicating the model's accuracy.

array([14.4431])

1.075145894175825

0.6319879120879122

0.9622414019607425

My Bagging Regressor Model is:96.22% correct


In [ ]:
import pickle
#Save model
with open('Main intern project.pkl', 'wb') as f:
    pickle.dump(model, f)

In [ ]:
import pickle
#load model
with open('Main intern project.pkl', 'rb') as f:
    model=pickle.load(f)

In [ ]:
!pip install streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 108.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 128.3 MB/s eta 0:00:00


In [ ]:
%%writefile app.py
import streamlit as st
import pandas as pd
import pickle
st.title('Car Selling Price Prediction App')

# Load the trained model
# Ensure 'Main intern project.pkl' is in the same directory as this app.py or provide the full path
with open('Main intern project.pkl', 'rb') as f:
    model = pickle.load(f)

st.header('Enter Car Details for Prediction')

# Input fields for features
year = st.slider('Manufacturing Year', min_value=2000, max_value=2024, value=2015)
present_price = st.number_input('Present Price (in Lakhs)', min_value=0.1, max_value=50.0, value=5.0, step=0.1)
kms_driven = st.number_input('Kilometers Driven', min_value=0, max_value=500000, value=30000, step=1000)

# Make prediction
if st.button('Predict Selling Price'):
    # Create a DataFrame from the inputs
    input_data = pd.DataFrame([{
        'Year': year,
        'Present_Price': present_price,
        'Kms_Driven': kms_driven
    }])

    # Predict
    prediction = model.predict(input_data)

    st.success(f'The predicted selling price is: {prediction[0]:.2f} Lakhs')

st.markdown("""
This app predicts the selling price of a car based on its manufacturing year,
present price, and kilometers driven using a pre-trained machine learning model.
""")

Writing app.py


In [ ]:
!streamlit run app.py




  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.245.97.105:8501

  Stopping...
  Stopping...
